---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    defaults
        mode tcp
        timeout connect 5s
        timeout client 10m
        timeout server 10m
        default-server init-addr last,libc,none

    resolvers k8s
        parse-resolv-conf
        hold valid 10s

    frontend redis_front
        bind *:6379
        default_backend redis_back

    backend redis_back
        mode tcp
        option tcp-check
        timeout check 3s
        tcp-check send PING\r\n
        tcp-check expect string +PONG
        tcp-check send info\ replication\r\n
        tcp-check expect string role:master
        server redis-0 redis-node-0.redis-headless.data.svc.cluster.local:6379 check on-marked-down shutdown-sessions inter 3s rise 2 fall 2 resolvers k8s resolve-prefer ipv4
        server redis-1 redis-node-1.redis-headless.data.svc.cluster.local:6379 check on-marked-down shutdown-sessions inter 3s rise 2 fall 2 resolvers k8s resolve-prefer ipv4
        server redis-2 redis-node-2.redis-headless.data.svc.cluster.local:6379 check on-marked-down shutdown-sessions inter 3s rise 2 fall 2 resolvers k8s resolve-prefer ipv4
