---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fastapi-scaler
  namespace: backend
spec:
  scaleTargetRef:
    name: fastapi-api
  minReplicaCount: 2
  maxReplicaCount: 20
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          # This replaces KEDA's cooldownPeriod. It tells the HPA to look back
          # over the last 5 minutes (300s) of high-frequency trading spikes
          # before deciding to scale down, preventing rapid pod churn.
          stabilizationWindowSeconds: 300
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 2
              periodSeconds: 15
            - type: Percent
              value: 25
              periodSeconds: 15
          selectPolicy: Max
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"
    - type: memory
      metricType: Utilization
      metadata:
        value: "70"
    - type: prometheus
      metadata:
        # Be sure this exactly matches the DNS name of your Prometheus service
        serverAddress: http://loki-stack-prometheus-server.monitoring.svc.cluster.local
        metricName: fastapi_concurrency
        threshold: "5"
        query: |
          sum(rate(http_request_duration_seconds_sum[1m]))
