---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-api
spec:
  template:
    spec:
      containers:
        - name: fastapi
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"