---
services:
  k8s-toolbox:
    build:
      context: .
      dockerfile: Dockerfile.toolbox
    container_name: k8s-toolbox
    tty: true
    stdin_open: true
    privileged: true
    user: root
    networks:
      - k3d-network
    volumes:
      - ${DOCKER_HOST_PATH:-/var/run/docker.sock}:/var/run/docker.sock:z
      - ../../:/workspace:z
      - ${HOST_ROOT}:${HOST_ROOT}:z
networks:
  k3d-network:
    name: k3d-network
