---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: trade-writer-scaler
  namespace: backend
spec:
  scaleTargetRef:
    name: trade-writer
  pollingInterval: 5
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: redis-streams
      metadata:
        addressFromEnv: REDIS_ADDRESS
        stream: INJECTED_BY_KUSTOMIZE # Placeholder
        consumerGroup: INJECTED_BY_KUSTOMIZE # Placeholder
        lagCount: "5000"
