---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/infrastructure

patches:
  - target:
      kind: HelmRelease
      name: loki-stack
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: loki-stack
      spec:
        values:
          prometheus:
            server:
              global:
                scrape_interval: 15s
  # - target:
  #     kind: HelmRelease
  #     name: "^(cnpg|keda)$"
  #   patch: |-
  #     - op: add
  #       path: /spec/dependsOn
  #       value:
  #         - name: loki-stack
  #           namespace: monitoring
