---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-infra
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/manifests/overlays/k3s/infrastructure 
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 2-data
  namespace: flux-system
spec:
  dependsOn:
    - name: 1-infra
  interval: 5m
  path: ./k8s/manifests/overlays/k3s/data-layer 
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 3-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: 2-data
  interval: 5m
  path: ./k8s/manifests/overlays/k3s/apps 
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
