---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-repo-will
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/WilliamTrump/equity-trading-system
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-stack
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: dev-repo-will
  path: ./k8s/manifests/overlays/dev-will
  prune: true
