---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: locust-ingress
  namespace: load-testing
spec:
  rules:
    - host: locust.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: locust-ui
                port:
                  number: 8089
