---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-api
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: ghcr.io/maxrabz/fastapi:working
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: "redis.backend.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_HOST
              value: "postgres.backend.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "trading"
          envFrom:
            - secretRef:
                name: db-credentials
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
