---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - loki-helm-repo.yaml
  - loki-helm-release.yaml
  - ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: custom-fastapi-dashboard
    namespace: monitoring
    files:
      - custom-dashboard.json=./dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        k8s-sidecar-target-directory: "Custom_Dashboards"
