---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/infrastructure
  - tailscale

patches:
  - path: monitoring-ingress-overwrite.yaml
  # - target:
  #     kind: HelmRelease
  #     name: "^(cnpg|keda)$"
  #   patch: |-
  #     - op: add
  #       path: /spec/dependsOn
  #       value:
  #         - name: loki-stack
  #           namespace: monitoring
