---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/infrastructure
  - tailscale
  - tailscale-route-fix.yaml

patches:
  - path: monitoring-ingress-overwrite.yaml
