---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/data-layer

patches:
  - target:
      kind: StatefulSet
      name: redis-node
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: doesnt-matter
      spec:
        template:
          spec:
            dnsConfig:
              options:
                - name: use-vc
