---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
spec:
  interval: 10m
  targetNamespace: keda
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
      version: "2.20.x" # Pin to a stable version
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
