---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis
  - redis-proxy
  - cnpg

configMapGenerator:
  - name: db-routing
    namespace: data
    envs:
      - ../shared-config/db-routing.env
    options:
      disableNameSuffixHash: true
  - name: redis-config
    namespace: data
    envs:
      - ../shared-config/redis-config.env
    options:
      disableNameSuffixHash: true
