---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres
  - redis
  - redis-proxy
  - pgbouncer

configMapGenerator:
  - name: db-routing
    namespace: data
    envs:
      - ../shared-config/db-routing.env
    options:
      disableNameSuffixHash: true
