---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/apps
  - streamlit-tailscale.yaml
  - streamlit-traefik.yaml
  - traefik-proxy.yaml

patches:
  - path: ingress-overwrite.yaml
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: streamlit-ingress
      $patch: delete

