---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamlit-traefik-internal
  namespace: frontend
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: networking-streamlit-fallback@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: ui
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: streamlit-svc
                port:
                  number: 80
    - host: ui.tailda280a.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: streamlit-svc
                port:
                  number: 80
