---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-syncer
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-syncer
  template:
    metadata:
      labels:
        app: db-syncer
    spec:
      initContainers:
        - name: wait-for-infra
          image: redis:8-alpine
          command:
            - sh
            - -c
            - |
              echo "{\"message\":\"Waiting for Redis, PgBouncer, and Loki...\"}"
              until redis-cli -h redis-proxy.data.svc.cluster.local PING | grep -q PONG && \
                    nc -z trading-pooler.data.svc.cluster.local 5432 && \
                    nc -z loki-stack.monitoring.svc.cluster.local 3100; do
                echo "{\"message\":\"Infrastructure not ready. Sleeping 5 second...\"}"
                sleep 5
              done
              echo "{\"message\":\"All infrastructure online! Booting db-syncer.\"}"
      containers:
        - name: db-syncer
          image: db-syncer-image
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD

            # Explicitly load the routing variables for interpolation
            - name: PG_ROUTING_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-routing
                  key: PG_ROUTING_HOST
            - name: PG_ROUTING_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-routing
                  key: PG_ROUTING_PORT
            - name: PG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-routing
                  key: PG_DATABASE

            # Build the connection string
            - name: POSTGRES_CONFIG
              value: "host=$(PG_ROUTING_HOST) port=$(PG_ROUTING_PORT) user=$(POSTGRES_USER) password=$(POSTGRES_PASSWORD) dbname=$(PG_DATABASE)"

            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_URL
            - name: RUST_LOG
              value: "debug"

            - name: DELAY
              value: "180"

            - name: LOKI_URL
              value: "http://loki-stack.monitoring.svc.cluster.local:3100"

            - name: WORKER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
