---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/apps

images:
  # - name: ghcr.io/sm26-industrial-software-dev/api
  #   newName: ghcr.io/maxrabz/fastapi
  # # newTag: working
  # - name: ghcr.io/sm26-industrial-software-dev/web-ui
  #   newName: ghcr.io/williamtrump/equity-trading-frontend
  # - name: ghcr.io/sm26-industrial-software-dev/db-syncer
  #   newName: ghcr.io/yscohen/db-syncer
  # - name: ghcr.io/sm26-industrial-software-dev/trade-writer
  #   newName: ghcr.io/yscohen/trade-writer
