---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: api-image
    newName: ghcr.io/sm26-industrial-software-dev/api
    newTag: latest
  - name: trade-writer-image
    newName: ghcr.io/sm26-industrial-software-dev/trade-writer:latest
  - name: db-syncer-image
    newName: ghcr.io/sm26-industrial-software-dev/db-syncer:latest
  - name: web-ui-image
    newName: ghcr.io/sm26-industrial-software-dev/web-ui:latest
  - name: price-cacher-image
    newName: ghcr.io/sm26-industrial-software-dev/price-cacher:latest
  - name: redis-populator-image
    newName: ghcr.io/sm26-industrial-software-dev/redis-populator:latest
  # - name: price-timeseries-cacher-image
  #   newName: ghcr.io/sm26-industrial-software-dev/price-timeseries-cacher:latest

resources:
  - error-pages
  - fastapi
  - locust
  - streamlit
  - trade-writer
  - db-syncer
  - adminer
  - redisinsight
  - price-cacher
  - redis-populator
  # - price-timeseries-cacher

configMapGenerator:
  - name: db-routing
    namespace: backend
    envs:
      - ../shared-config/db-routing.env
    options:
      disableNameSuffixHash: true
  - name: redis-config
    namespace: backend
    envs:
      - ../shared-config/redis-config.env
    options:
      disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: redis-config
      namespace: backend
      fieldPath: data.REDIS_STREAM_NAME
    targets:
      - select:
          kind: ScaledObject
          name: trade-writer-scaler
        fieldPaths:
          - spec.triggers.*.metadata.stream
  - source:
      kind: ConfigMap
      name: redis-config
      namespace: backend
      fieldPath: data.REDIS_CONSUMER_GROUP
    targets:
      - select:
          kind: ScaledObject
          name: trade-writer-scaler
        fieldPaths:
          - spec.triggers.*.metadata.consumerGroup
