---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: backend
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          args:
            - "-c"
            - "log_statement=all"
            - "-c"
            - "log_connections=on"
            - "-c"
            - "log_disconnections=on"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "trading"
          envFrom:
            - secretRef:
                name: db-credentials
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-schema
              mountPath: /docker-entrypoint-initdb.d/01-schema.sql
              subPath: 01-schema.sql
      volumes:
        - name: init-schema
          configMap:
            name: postgres-init-schema
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
