---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-populator
spec:
  schedule: "0 0 31 2 *" # Dummy schedule (Feb 31st - never)
  suspend: true
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 15
      template:
        metadata:
          labels:
            app: redis-populator
        spec:
          restartPolicy: OnFailure
          containers:
            - name: populator
              image: redis-populator-image
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: "25m"
                  memory: "32Mi"
                limits:
                  cpu: "100m"
                  memory: "128Mi"
              env:
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: db-credentials
                      key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-credentials
                      key: POSTGRES_PASSWORD
                - name: PG_ROUTING_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: db-routing
                      key: PG_ROUTING_HOST
                - name: PG_ROUTING_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: db-routing
                      key: PG_ROUTING_PORT
                - name: PG_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: db-routing
                      key: PG_DATABASE
                - name: POSTGRES_CONFIG
                  value: "host=$(PG_ROUTING_HOST) port=$(PG_ROUTING_PORT) user=$(POSTGRES_USER) password=$(POSTGRES_PASSWORD) dbname=$(PG_DATABASE)"
                - name: REDIS_URL
                  valueFrom:
                    configMapKeyRef:
                      name: redis-config
                      key: REDIS_URL
                - name: RUST_LOG
                  value: "debug"
                - name: LOKI_URL
                  value: "http://loki-stack.monitoring.svc.cluster.local:3100"
                - name: WORKER_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
