# syntax=docker/dockerfile:1

# to build, pass name of desired bin. for example:
# --build-arg BIN_NAME=trade-writer

FROM --platform=$BUILDPLATFORM lukemathwalker/cargo-chef:latest AS planner
WORKDIR /app
COPY . .
RUN cargo chef prepare --recipe-path recipe.json


# --- base stage for both builders ---
FROM --platform=$BUILDPLATFORM lukemathwalker/cargo-chef:latest AS builder-base
WORKDIR /app
RUN apt-get update && apt-get install -y \
    musl-tools \
    wget \
    && rm -rf /var/lib/apt/lists/*
#   ^ reduce layer size by deleting apt lists



# --- for amd64 compilation ---
FROM builder-base AS builder-amd64
ENV RUST_TARGET=x86_64-unknown-linux-musl
ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=musl-gcc
ENV CC_x86_64_unknown_linux_musl=musl-gcc


# --- for arm64 cross-compilation ---
FROM builder-base AS builder-arm64
ENV RUST_TARGET=aarch64-unknown-linux-musl
RUN wget -q https://musl.cc/aarch64-linux-musl-cross.tgz && \
    tar -xzf aarch64-linux-musl-cross.tgz -C /usr/local && \
    rm aarch64-linux-musl-cross.tgz
ENV PATH="/usr/local/aarch64-linux-musl-cross/bin:${PATH}"
ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-musl-gcc
ENV CC_aarch64_unknown_linux_musl=aarch64-linux-musl-gcc
ENV CXX_aarch64_unknown_linux_musl=aarch64-linux-musl-g++


ARG TARGETARCH
FROM builder-${TARGETARCH} AS builder

RUN rustup target add $RUST_TARGET

COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --target $RUST_TARGET --recipe-path recipe.json

COPY . .
ARG BIN_NAME
RUN cargo build --release --target $RUST_TARGET --bin $BIN_NAME && \
    cp target/$RUST_TARGET/release/$BIN_NAME /app-binary


# final stage assumes the platform requested in the build command
FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app-binary /app-binary

ENTRYPOINT ["/app-binary"]
