---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 10m
  chart:
    spec:
      chart: redis
      version: "18.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    architecture: replication
    auth:
      enabled: false
    metrics:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/redis-exporter
        tag: "latest"

    commonConfiguration: |-
      appendonly yes
      appendfsync everysec
      save 60 1
      save 300 10
      dir /data
      loadmodule /opt/redis-modules/redistimeseries.so

    image:
      registry: docker.io
      repository: bitnami/redis
      tag: "latest"

    sentinel:
      enabled: true
      masterSet: mymaster
      quorum: 2
      image:
        registry: docker.io
        repository: bitnami/redis-sentinel
        tag: "latest"

    master:
      extraVolumes:
        - name: redis-modules
          emptyDir: {}
      extraVolumeMounts:
        - name: redis-modules
          mountPath: /opt/redis-modules
      initContainers:
        - name: copy-module
          image: redis/redis-stack-server:latest
          command: ["sh", "-c", "cp /opt/redis-stack/lib/redistimeseries.so /opt/redis-modules/"]
          volumeMounts:
            - name: redis-modules
              mountPath: /opt/redis-modules
      persistence:
        enabled: true
        size: 2Gi
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 256Mi

    replica:
      replicaCount: 3
      extraVolumes:
        - name: redis-modules
          emptyDir: {}
      extraVolumeMounts:
        - name: redis-modules
          mountPath: /opt/redis-modules
      initContainers:
        - name: copy-module
          image: redis/redis-stack-server:latest
          command: ["sh", "-c", "cp /opt/redis-stack/lib/redistimeseries.so /opt/redis-modules/"]
          volumeMounts:
            - name: redis-modules
              mountPath: /opt/redis-modules
      persistence:
        enabled: true
        size: 2Gi
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 256Mi
